#!/usr/bin/env python3
"""Pose Guide — Image collector and manifest generator.

Usage:
    python3 collect.py pdf /path/to/file.pdf --type maternity
    python3 collect.py folder ~/Downloads/pose_refs/ --type family
    python3 collect.py refresh          # Regenerate manifest.js from images/
    python3 collect.py build            # Same as refresh (alias)
    python3 collect.py build-offline    # Single HTML with all images inlined (AirDrop to iPhone)
"""

import argparse
import base64
import hashlib
import json
import mimetypes
import shutil
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
IMAGES_DIR = SCRIPT_DIR / "images"
MANIFEST_JS = SCRIPT_DIR / "manifest.js"
VALID_CATEGORIES = [
    "baby shower", "maternity", "family", "kids", "couples", "newborn", "wedding", "uncategorized"
]
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".tiff", ".tif", ".heic"}

# PDF extraction filters
MIN_IMAGE_BYTES = 15_000   # Skip images < 15KB (logos, icons, separators)
MIN_IMAGE_DIM = 150        # Skip images with width or height < 150px


def file_hash(path: Path) -> str:
    """SHA-256 hash of file contents for deduplication."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def bytes_hash(data: bytes) -> str:
    """SHA-256 hash of raw bytes."""
    return hashlib.sha256(data).hexdigest()


def existing_hashes(category_dir: Path) -> set:
    """Collect hashes of all images already in a category folder."""
    hashes = set()
    if not category_dir.exists():
        return hashes
    for f in category_dir.iterdir():
        if f.is_file() and f.suffix.lower() in IMAGE_EXTS:
            hashes.add(file_hash(f))
    return hashes


def get_next_number(category_dir: Path) -> int:
    """Find the next sequential number for naming."""
    if not category_dir.exists():
        return 1
    nums = []
    for f in category_dir.iterdir():
        if not f.is_file():
            continue
        parts = f.stem.rsplit("_", 1)
        if len(parts) == 2:
            try:
                nums.append(int(parts[1]))
            except ValueError:
                pass
    return max(nums, default=0) + 1


def normalize_ext(ext: str) -> str:
    """Normalize extension but preserve format."""
    ext = ext.lower()
    if ext == ".jpeg":
        return ".jpg"
    if ext == ".tiff":
        return ".tif"
    return ext


def refresh_manifest():
    """Regenerate manifest.js from current images/ contents."""
    manifest = {}
    for cat_dir in sorted(IMAGES_DIR.iterdir()):
        if not cat_dir.is_dir() or cat_dir.name.startswith("."):
            continue
        files = sorted(
            f.name for f in cat_dir.iterdir()
            if f.is_file() and f.suffix.lower() in IMAGE_EXTS
        )
        if files:
            manifest[cat_dir.name] = files

    # Write as JS variable — works from file:// without fetch
    js_content = "// Auto-generated by collect.py — do not edit\n"
    js_content += "window.POSE_MANIFEST = " + json.dumps(manifest, indent=2) + ";\n"
    MANIFEST_JS.write_text(js_content)

    total = sum(len(v) for v in manifest.values())
    print(f"Manifest updated: {total} images across {len(manifest)} categories")
    for cat, files in manifest.items():
        print(f"  {cat}: {len(files)}")


def import_from_folder(source: Path, category: str, move: bool = False):
    """Copy/move images from a folder into the category directory, with dedup."""
    cat_dir = IMAGES_DIR / category
    cat_dir.mkdir(parents=True, exist_ok=True)
    known = existing_hashes(cat_dir)
    num = get_next_number(cat_dir)
    imported = 0
    skipped_dup = 0

    files = sorted(source.iterdir()) if source.is_dir() else [source]
    for f in files:
        if not f.is_file() or f.suffix.lower() not in IMAGE_EXTS:
            continue

        h = file_hash(f)
        if h in known:
            print(f"  SKIP (duplicate): {f.name}")
            skipped_dup += 1
            continue
        known.add(h)

        ext = normalize_ext(f.suffix)
        dest = cat_dir / f"{category}_{num:03d}{ext}"
        if move:
            shutil.move(str(f), dest)
        else:
            shutil.copy2(str(f), dest)
        print(f"  {f.name} -> {dest.name}")
        num += 1
        imported += 1

    print(f"\nImported {imported} images to images/{category}/")
    if skipped_dup:
        print(f"Skipped {skipped_dup} duplicates")
    refresh_manifest()


def extract_from_pdf(pdf_path: Path, category: str):
    """Extract embedded images from a PDF file with junk filtering + dedup."""
    try:
        import fitz  # PyMuPDF
    except ImportError:
        print("PyMuPDF not installed. Run: pip3 install PyMuPDF")
        sys.exit(1)

    cat_dir = IMAGES_DIR / category
    cat_dir.mkdir(parents=True, exist_ok=True)
    known = existing_hashes(cat_dir)
    num = get_next_number(cat_dir)
    imported = 0
    skipped_small = 0
    skipped_dup = 0

    doc = fitz.open(str(pdf_path))
    print(f"Scanning {doc.page_count} pages in {pdf_path.name}...")

    seen_xrefs = set()  # Same image can appear on multiple pages

    for page_num in range(doc.page_count):
        page = doc[page_num]
        for img_info in page.get_images(full=True):
            xref = img_info[0]
            if xref in seen_xrefs:
                continue
            seen_xrefs.add(xref)

            base_image = doc.extract_image(xref)
            if not base_image:
                continue

            img_bytes = base_image["image"]
            width = base_image.get("width", 0)
            height = base_image.get("height", 0)

            # Filter junk: too small in bytes
            if len(img_bytes) < MIN_IMAGE_BYTES:
                skipped_small += 1
                continue
            # Filter junk: too small in dimensions
            if width < MIN_IMAGE_DIM or height < MIN_IMAGE_DIM:
                skipped_small += 1
                continue

            # Deduplicate by content hash
            h = bytes_hash(img_bytes)
            if h in known:
                skipped_dup += 1
                continue
            known.add(h)

            ext = normalize_ext("." + base_image["ext"])
            dest = cat_dir / f"{category}_{num:03d}{ext}"
            dest.write_bytes(img_bytes)
            print(f"  Page {page_num + 1}: {dest.name} ({width}x{height}, {len(img_bytes) // 1024}KB)")
            num += 1
            imported += 1

    doc.close()
    print(f"\nExtracted {imported} images to images/{category}/")
    if skipped_small:
        print(f"Filtered {skipped_small} small/junk images")
    if skipped_dup:
        print(f"Skipped {skipped_dup} duplicates")
    refresh_manifest()


def build_offline():
    """Build a single self-contained HTML with all images base64-inlined."""
    html_path = SCRIPT_DIR / "pose_guide.html"
    out_path = SCRIPT_DIR / "pose_guide_offline.html"

    if not html_path.exists():
        print("Error: pose_guide.html not found")
        sys.exit(1)

    # Build manifest with base64 data URIs instead of file paths
    manifest = {}
    total_images = 0
    for cat_dir in sorted(IMAGES_DIR.iterdir()):
        if not cat_dir.is_dir() or cat_dir.name.startswith("."):
            continue
        images = []
        for f in sorted(cat_dir.iterdir()):
            if not f.is_file() or f.suffix.lower() not in IMAGE_EXTS:
                continue
            mime = mimetypes.guess_type(f.name)[0] or "image/png"
            b64 = base64.b64encode(f.read_bytes()).decode("ascii")
            images.append({"name": f.name, "data": f"data:{mime};base64,{b64}"})
            total_images += 1
        if images:
            manifest[cat_dir.name] = images

    # Read the original HTML
    html = html_path.read_text()

    # Replace the manifest.js script tag with inline data
    # The HTML loads: <script src="manifest.js"></script>
    # Replace with inline manifest that uses data URIs
    manifest_js = "window.POSE_MANIFEST = {};\n"
    manifest_js += "window.POSE_MANIFEST_INLINE = true;\n"
    manifest_js += "window.POSE_DATA = " + json.dumps(
        {cat: {img["name"]: img["data"] for img in imgs} for cat, imgs in manifest.items()}
    ) + ";\n"
    # Build standard manifest (just filenames) for category rendering
    manifest_js += "window.POSE_MANIFEST = " + json.dumps(
        {cat: [img["name"] for img in imgs] for cat, imgs in manifest.items()}
    ) + ";\n"

    html = html.replace(
        '<script src="manifest.js"></script>',
        f"<script>\n{manifest_js}</script>"
    )

    # Patch the JS to use data URIs for image sources
    # Replace image src construction: 'images/' + cat + '/' + f  →  POSE_DATA[cat][f]
    html = html.replace(
        "src: 'images/' + cat + '/' + f,",
        "src: (window.POSE_DATA && window.POSE_DATA[cat]) ? window.POSE_DATA[cat][f] : 'images/' + cat + '/' + f,"
    )

    out_path.write_text(html)
    size_mb = out_path.stat().st_size / (1024 * 1024)
    print(f"Built: {out_path.name} ({size_mb:.1f} MB, {total_images} images)")
    print("AirDrop this file to iPhone → open in Safari → works fully offline")


def main():
    parser = argparse.ArgumentParser(description="Pose Guide image collector")
    sub = parser.add_subparsers(dest="command")

    # refresh / build
    sub.add_parser("refresh", help="Regenerate manifest.js from current images/")
    sub.add_parser("build", help="Alias for refresh")
    sub.add_parser("build-offline", help="Single HTML with all images inlined for iPhone")

    # folder
    folder_p = sub.add_parser("folder", help="Import images from a folder")
    folder_p.add_argument("source", type=Path, help="Source folder or single image")
    folder_p.add_argument("--type", required=True, dest="category",
                          choices=VALID_CATEGORIES, help="Shoot type category")
    folder_p.add_argument("--move", action="store_true", help="Move instead of copy")

    # pdf
    pdf_p = sub.add_parser("pdf", help="Extract images from a PDF")
    pdf_p.add_argument("source", type=Path, help="Path to PDF file")
    pdf_p.add_argument("--type", required=True, dest="category",
                        choices=VALID_CATEGORIES, help="Shoot type category")

    args = parser.parse_args()

    if args.command == "build-offline":
        build_offline()
    elif args.command in ("refresh", "build"):
        refresh_manifest()
    elif args.command == "folder":
        if not args.source.exists():
            print(f"Error: {args.source} not found")
            sys.exit(1)
        import_from_folder(args.source, args.category)
    elif args.command == "pdf":
        if not args.source.exists():
            print(f"Error: {args.source} not found")
            sys.exit(1)
        extract_from_pdf(args.source, args.category)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
